import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/Navbar";
import Footer from "@/components/custom/Footer";
import { Toaster } from "sonner";
import { AuthProvider } from "@/lib/context/AuthContext";

const giest = Geist({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "JobGhar | Your Job Search Companion",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${giest.className} flex flex-col min-h-screen`}>
        <AuthProvider>
          <Header />
          <main className="flex-grow">
            {children}
            <Toaster />
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
